name: Flarum Build
on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@master
            -   uses: flarum/action-build@2
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
