name: Build changelog
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch:
        inputs:
            next_version:
                description: "Next version tag"
                required: false

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: recursive
            -   uses: maicol07/github-changelog-action@patch-1
                with:
                    next_version: ${{ github.event.inputs.next_version }}
            -   uses: oleksiyrudenko/gha-git-credentials@v2-latest
                with:
                    token: '${{ secrets.GITHUB_TOKEN }}'
            -   run: "git commit -m \"release: 🔖 Updated changelog\" -a"
            -   name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ github.ref }}
