name: Build changelog
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            -   uses: bscs-science-learning/github-changelog-action@master
                with:
                    next_version: "1.10.1"
