name: Build changelog
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: recursive
            -   uses: maicol07/github-changelog-action@patch-1
                with:
                    next_version: "1.10.1"
            -   name: Push changes
                uses: ad-m/github-push-action@master
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    branch: ${{ github.ref }}
