name: Build changelog
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0
                    submodules: recursive
            -   uses: nwillems/github-changelog-action@patch-1
                with:
                    next_version: "1.10.1"
                    filename: CHANGELOG.md
