name: Build changelog
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            -   uses: nwillems/github-changelog-action@patch-1
                with:
                    config_dir: chglog/.chglog
                    next_version: "1.10"
